#!/usr/bin/env python

Import("env")
Import("env_modules")

env_flow_script = env_modules.Clone()

env_flow_script.add_source_files(env.modules_sources, "*.cpp")
env_flow_script.add_source_files(env.modules_sources, "./nodes/*.cpp")

if env.editor_build:
	env_flow_script.add_source_files(env.modules_sources, "./editor/*.cpp")
	env_flow_script.add_source_files(env.modules_sources, "./editor/gui/*.cpp")
	env_flow_script.add_source_files(env.modules_sources, "./editor/nodes/*.cpp")
	env_flow_script.add_source_files(env.modules_sources, "./editor/plugins/*.cpp")
