@tool
extends RefCounted

const data: Array[Dictionary] = [
	{
		id = "comment",
		name = "Comment",
		category = "Flow",
		description = "An inconsequential text box.\nWrite whatever you want.",
		object_path = "nodes/objects/comment.gd",
		editor_path = "nodes/editors/comment.tscn",
		automatically_assign_id = true,
	},
	{
		id = "procedure",
		name = "Procedure",
		category = "Flow",
		description = "Marks the beginning of a Flow procedure.\nNodes of this type can be renamed.",
		object_path = "nodes/objects/procedure.gd",
		editor_path = "nodes/editors/procedure.tscn",
		automatically_assign_id = false,
	},
	{
		id = "return",
		name = "Return Value",
		category = "Flow",
		description = "Ends execution of a procedure and returns a value to the caller.",
		object_path = "nodes/objects/return.gd",
		editor_path = "nodes/editors/return.tscn",
		automatically_assign_id = true,
	},
	#{
		#id = "expression_execute",
		#name = "Execute Expressions",
		#category = "Flow",
		#description = "Executes a series of expressions.",
		#object_path = "nodes/objects/expression_execute.gd",
		#editor_path = "nodes/editors/expression_execute.gd",
	#},
	{
		id = "expression_branch",
		name = "Conditional Branch",
		category = "Flow",
		description = "Branches one way or another depending on whether or not the expressions written evaluate to true.",
		object_path = "nodes/objects/expression_branch.gd",
		editor_path = "nodes/editors/expression_branch.tscn",
		automatically_assign_id = true,
	},
	{
		id = "while_expression_loop",
		name = "While Loop",
		category = "Flow",
		description = "Executes a block of code repeatedly as long as the expression written evaluates to true.",
		object_path = "nodes/objects/while_expression_loop.gd",
		editor_path = "nodes/editors/while_expression_loop.tscn",
		automatically_assign_id = true,
	},
	{
		id = "set_local",
		name = "Set Local Variable",
		category = "Flow",
		description = "Assigns a local variable to the result of some expression.",
		object_path = "nodes/objects/set_local.gd",
		editor_path = "nodes/editors/set_variable.tscn",
		automatically_assign_id = true,
	},
	{
		id = "set_global",
		name = "Set Global Variable",
		category = "Flow",
		description = "Assigns a global variable to the result of some expression.",
		object_path = "nodes/objects/set_global.gd",
		editor_path = "nodes/editors/set_variable.tscn",
		automatically_assign_id = true,
	},
]
