@tool
extends RefCounted

const data: Array[Dictionary] = [
	{
		id = "comment",
		name = "Comment",
		category = "",
		description = "An inconsequential text box.\nWrite whatever you want.",
		object_path = "nodes/objects/comment.gd",
		editor_path = "nodes/editors/comment.tscn",
		automatically_assign_id = true,
	},
	{
		id = "wait_seconds",
		name = "Wait",
		category = "",
		description = "Waits a set time before progressing.",
		object_path = "nodes/objects/wait_seconds.gd",
		editor_path = "nodes/editors/wait_seconds.tscn",
		automatically_assign_id = true,
	},
	{
		id = "console_print",
		name = "Print",
		category = "Debug",
		description = "Prints some message to the console.\nAn expression box is provided in case you need to format the string." ,
		object_path = "nodes/objects/console_print.gd",
		editor_path = "nodes/editors/console_print.tscn",
		automatically_assign_id = true,
	},
	{
		id = "procedure",
		name = "Procedure",
		category = "Flow",
		description = "Marks the beginning of a Flow procedure.\nNodes of this type can be renamed.",
		object_path = "nodes/objects/procedure.gd",
		editor_path = "nodes/editors/procedure.tscn",
		automatically_assign_id = false,
	},
	{
		id = "return",
		name = "Return Value",
		category = "Flow",
		description = "Ends execution of a procedure and returns a value to the caller.",
		object_path = "nodes/objects/return.gd",
		editor_path = "nodes/editors/return.tscn",
		automatically_assign_id = true,
	},
	{
		id = "expression_execute",
		name = "Execute Expressions",
		category = "Flow",
		description = "Executes a series of expressions.",
		object_path = "nodes/objects/expression_execute.gd",
		editor_path = "nodes/editors/expression_execute.tscn",
		automatically_assign_id = true,
	},
	{
		id = "expression_branch",
		name = "Conditional Branch",
		category = "Flow/Control",
		description = "Branches one way or another depending on whether or not the expressions written evaluate to true.",
		object_path = "nodes/objects/expression_branch.gd",
		editor_path = "nodes/editors/expression_branch.tscn",
		automatically_assign_id = true,
	},
	{
		id = "while_expression_loop",
		name = "While Loop",
		category = "Flow/Control",
		description = "Executes a block of code repeatedly as long as the expression written evaluates to true.",
		object_path = "nodes/objects/while_expression_loop.gd",
		editor_path = "nodes/editors/while_expression_loop.tscn",
		automatically_assign_id = true,
	},
	{
		id = "sequential_branch_execute",
		name = "Execute Branches Sequentially",
		category = "Flow/Control",
		description = "Executes branches one after another and waits for their completion.",
		object_path = "nodes/objects/sequential_branch_execute.gd",
		editor_path = "nodes/editors/multi_branch_execute.tscn",
		automatically_assign_id = true,
	},
	{
		id = "simultaneous_branch_execute",
		name = "Execute Branches Simultaneously",
		category = "Flow/Control",
		description = "Executes branches simultaneously, then proceeds once all of them have finished execution.",
		object_path = "nodes/objects/simultaneous_branch_execute.gd",
		editor_path = "nodes/editors/multi_branch_execute.tscn",
		automatically_assign_id = true,
	},
	{
		id = "set_local",
		name = "Set Local Variable",
		category = "Flow/Variables",
		description = "Assigns a local variable to the result of some expression.",
		object_path = "nodes/objects/set_local.gd",
		editor_path = "nodes/editors/set_variable.tscn",
		automatically_assign_id = true,
	},
	{
		id = "set_global",
		name = "Set Global Variable",
		category = "Flow/Variables",
		description = "Assigns a global variable to the result of some expression.",
		object_path = "nodes/objects/set_global.gd",
		editor_path = "nodes/editors/set_variable.tscn",
		automatically_assign_id = true,
	},
]
